---
- name: Creates directory n
  file:
    path: ~/web-app
    state: directory
  
- name: Unarchive Web App
  unarchive:
    src: demo-webapp.gz
    dest: ~/web-app
  
- name: "start app"
  shell: |       
      pm2 serve build 3000
  args: 
    chdir: ~/web-app/demo-webapp
  register: pm2
  ignore_errors: true

- name: Run only if the task that registered the "result" variable fails
  shell: |      
    pm2 reload -f
  when: pm2 is failed

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines