---
- name: Creates directory n
  file:
    path: ~/web-app
    state: directory
  
- name: Unarchive Web App
  unarchive:
    src: demo-webapp.gz
    dest: ~/web-app
  
- name: "start app"
  shell: |       
      serve build 3000 
  args: 
    chdir: ~/web-app/demo-webapp

- name: "List processes"
  shell: |      
      pm2 list
  register: pm2_result 

- name: "Print in the debug console"
  debug:
    var: pm2_result.stdout_lines